[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
minter = "2vPErEWHjdGAv5JBYYN72X1UR51sAFJ3LHVHnqaEinJH"
oracle = "7WS182qgZYwY2wiqZkX5LBvw43fsfkHtp9kKCXtF5kXp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://devnet.helius-rpc.com/?api-key=b9c69888-36d9-452b-9c52-a4ee1d8fcf23"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
